# Generated by Django 6.0.2 on 2026-02-18 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_cancelled_at_alter_order_status'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_provide_3e1786_idx',
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cod', 'Cash on delivery'), ('stripe', 'Stripe'), ('payme', 'Payme (Paycom)'), ('click', 'Click')], default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_ref',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order'),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='provider_payment_id',
        ),
    ]
