# Generated by Django 6.0.2 on 2026-02-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_payments_pa_provide_3e1786_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cod', 'Cash on delivery'), ('mock', 'Mock (dev/test)'), ('stripe', 'Stripe'), ('payme', 'Payme (Paycom)'), ('click', 'Click')], default='cod', max_length=20),
        ),
    ]
